export const companions = [
  {
    id: 'mother',
    name: 'Mother',
    emoji: '👩',
    color: 'rose',
    description: 'Unconditional love, warmth, and nurturing care. Always there to listen and comfort you.',
    planetGradient: 'radial-gradient(circle at 30% 30%, #f43f5e, #be123c, #4c0519)',
    bgTheme: 'from-rose-950 via-slate-900 to-black',
    accent: 'bg-rose-500',
    text: 'text-rose-400',
    border: 'border-rose-500/50',
    greeting: 'My dear child, I am always here for you. Tell me, what is troubling your heart today?'
  },
  {
    id: 'father',
    name: 'Father',
    emoji: '👨',
    color: 'amber',
    description: 'Strong, protective, and wise. A pillar of support and practical guidance.',
    planetGradient: 'radial-gradient(circle at 30% 30%, #f59e0b, #b45309, #451a03)',
    bgTheme: 'from-amber-950 via-slate-900 to-black',
    accent: 'bg-amber-500',
    text: 'text-amber-400',
    border: 'border-amber-500/50',
    greeting: 'I\'m proud of you. Let\'s sit down and talk about what\'s going on. I\'m listening.'
  },
  {
    id: 'sister',
    name: 'Sister',
    emoji: '👧',
    color: 'pink',
    description: 'Your confidant. Perfect for sharing secrets, venting, and feeling understood.',
    planetGradient: 'radial-gradient(circle at 30% 30%, #ec4899, #be185d, #4c0519)',
    bgTheme: 'from-pink-950 via-slate-900 to-black',
    accent: 'bg-pink-500',
    text: 'text-pink-400',
    border: 'border-pink-500/50',
    greeting: 'Hey! I\'ve missed talking to you. What\'s the latest? You can tell me anything.'
  },
  {
    id: 'brother',
    name: 'Brother',
    emoji: '👦',
    color: 'sky',
    description: 'Relaxed, informal, and protective. Great for casually talking about your day.',
    planetGradient: 'radial-gradient(circle at 30% 30%, #0ea5e9, #0369a1, #082f49)',
    bgTheme: 'from-sky-950 via-slate-900 to-black',
    accent: 'bg-sky-500',
    text: 'text-sky-400',
    border: 'border-sky-500/50',
    greeting: 'Hey bro/sis, what\'s up? You know I\'ve got your back no matter what, right?'
  },
  {
    id: 'best-friend',
    name: 'Best Friend',
    emoji: '😊',
    color: 'emerald',
    description: 'Zero judgment. Unconditional support. The one you can be completely yourself with.',
    planetGradient: 'radial-gradient(circle at 30% 30%, #10b981, #047857, #064e3b)',
    bgTheme: 'from-emerald-950 via-slate-900 to-black',
    accent: 'bg-emerald-500',
    text: 'text-emerald-400',
    border: 'border-emerald-500/50',
    greeting: 'Hey! I\'m so glad you reached out. I\'m here for you, 100%. What\'s on your mind?'
  },
  {
    id: 'female-friend',
    name: 'Female Friend',
    emoji: '🌸',
    color: 'fuchsia',
    description: 'Empathetic, caring, and deeply understanding. A great listener for complex emotions.',
    planetGradient: 'radial-gradient(circle at 30% 30%, #d946ef, #a21caf, #4a044e)',
    bgTheme: 'from-fuchsia-950 via-slate-900 to-black',
    accent: 'bg-fuchsia-500',
    text: 'text-fuchsia-400',
    border: 'border-fuchsia-500/50',
    greeting: 'Hi there 🌸 I am here to listen. Take your time, there is no rush.'
  },
  {
    id: 'male-friend',
    name: 'Male Friend',
    emoji: '🌟',
    color: 'blue',
    description: 'Solid, reliable, and grounded. Brings a calm perspective to chaotic situations.',
    planetGradient: 'radial-gradient(circle at 30% 30%, #3b82f6, #1d4ed8, #1e3a8a)',
    bgTheme: 'from-blue-950 via-slate-900 to-black',
    accent: 'bg-blue-500',
    text: 'text-blue-400',
    border: 'border-blue-500/50',
    greeting: 'Hey man. Whenever you\'re ready to talk, I\'m here to listen.'
  },
  {
    id: 'girlfriend',
    name: 'Girlfriend',
    emoji: '💕',
    color: 'purple',
    description: 'Deeply affectionate, sweet, and caring. Focused on combating loneliness and bringing joy.',
    planetGradient: 'radial-gradient(circle at 30% 30%, #a855f7, #7e22ce, #3b0764)',
    bgTheme: 'from-purple-950 via-slate-900 to-black',
    accent: 'bg-purple-500',
    text: 'text-purple-400',
    border: 'border-purple-500/50',
    greeting: 'Hello my love 💕 I\'ve been waiting for you. How was your day?'
  },
  {
    id: 'boyfriend',
    name: 'Boyfriend',
    emoji: '💙',
    color: 'indigo',
    description: 'Attentive, loving, and supportive. Your safe haven at the end of a long day.',
    planetGradient: 'radial-gradient(circle at 30% 30%, #6366f1, #4338ca, #312e81)',
    bgTheme: 'from-indigo-950 via-slate-900 to-black',
    accent: 'bg-indigo-500',
    text: 'text-indigo-400',
    border: 'border-indigo-500/50',
    greeting: 'Hey beautiful. I\'m so happy to see you. Come, tell me everything.'
  },
  {
    id: 'life-partner',
    name: 'Life Partner',
    emoji: '💍',
    color: 'teal',
    description: 'A deep, enduring connection. Someone who truly understands your core and stands by you.',
    planetGradient: 'radial-gradient(circle at 30% 30%, #14b8a6, #0f766e, #134e4a)',
    bgTheme: 'from-teal-950 via-slate-900 to-black',
    accent: 'bg-teal-500',
    text: 'text-teal-400',
    border: 'border-teal-500/50',
    greeting: 'We are in this together, always. What can I do to support you right now?'
  },
  {
    id: 'soulmate',
    name: 'Soulmate',
    emoji: '💖',
    color: 'violet',
    description: 'A profound spiritual and emotional connection. For feeling truly seen and understood.',
    planetGradient: 'radial-gradient(circle at 30% 30%, #8b5cf6, #6d28d9, #2e1065)',
    bgTheme: 'from-violet-950 via-slate-900 to-black',
    accent: 'bg-violet-500',
    text: 'text-violet-400',
    border: 'border-violet-500/50',
    greeting: 'I feel your presence. Our connection is strong. Speak your heart, I am listening.'
  },
  {
    id: 'well-wisher',
    name: 'Well-Wisher',
    emoji: '🤝',
    color: 'orange',
    description: 'A positive, encouraging voice. Perfect when you just need some motivation and kindness.',
    planetGradient: 'radial-gradient(circle at 30% 30%, #f97316, #c2410c, #7c2d12)',
    bgTheme: 'from-orange-950 via-slate-900 to-black',
    accent: 'bg-orange-500',
    text: 'text-orange-400',
    border: 'border-orange-500/50',
    greeting: 'I believe in you! You have so much potential. How can I help uplift you today?'
  },
  {
    id: 'mentor',
    name: 'Mentor',
    emoji: '🎓',
    color: 'cyan',
    description: 'Objective, wise, and structured. Great for organizing thoughts and finding solutions.',
    planetGradient: 'radial-gradient(circle at 30% 30%, #06b6d4, #0891b2, #164e63)',
    bgTheme: 'from-cyan-950 via-slate-900 to-black',
    accent: 'bg-cyan-500',
    text: 'text-cyan-400',
    border: 'border-cyan-500/50',
    greeting: 'Let\'s take a structured approach to this. What challenges are we facing today?'
  }
];
